name: Artifact Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dummy file
        run: |
          echo "This is a dummy artifact file." > dummy.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-artifact
          path: dummy.txt
